name: Telekinesis
version: '${project.version}'
main: org.mooner510.telekinesis.Telekinesis
api-version: '1.19'
authors: [Mooner510]

commands:
  autopickup:
    aliases: [자동줍기]
  autosmelt:
    aliases: [자동굽기]